from typing import Dict, Any, Literal, List
from pydantic import BaseModel
from core.rotator import GeminiKeyRotator
from core.models import ProjectState
from config.keys import GEMINI_MODEL_NAME

class SupervisorDecision(BaseModel):
    next_agent: Literal["researcher", "coding_crew", "data_crew", "content_crew", "FINISH"]
    instruction: str
    reasoning: str

class OrchestratorAgent:
    """
    [SWARM 2.0] Orchestrator Agent
    具备无限记忆管理能力的多模态超级调度器。
    """
    def __init__(self, rotator: GeminiKeyRotator, system_instruction: str):
        self.rotator = rotator
        self.system_instruction = system_instruction
        self.model = GEMINI_MODEL_NAME
        self.max_history_turns = 15

    def _summarize_old_memory(self, history_to_compress: List[Dict]) -> str:
        """调用 LLM 将旧对话压缩成摘要"""
        # ... (保持原有的摘要逻辑不变) ...
        print("🧠 [Memory] 正在压缩长期记忆...")
        text_content = ""
        for h in history_to_compress:
            role = h.get('role', 'unknown')
            text = h.get('parts', [{}])[0].get('text', '')
            text_content += f"{role}: {text}\n"
            
        prompt = f"Summarize this:\n{text_content}" # 简化示意
        try:
             # 这里为了简化，直接调用 text prompt，不涉及图片
            summary = self.rotator.call_gemini_with_rotation(
                model_name=self.model,
                contents=[{"role": "user", "parts": [{"text": prompt}]}],
                system_instruction="You are a memory compressor."
            )
            return summary or ""
        except: return ""

    def run(self, state: Dict[str, Any]) -> Dict[str, Any]:
        current_state = state.get("project_state")
        if not current_state: return {}

        # --- [Step 1: 记忆管理] ---
        # (保持原有的记忆压缩逻辑)
        if len(current_state.full_chat_history) > self.max_history_turns:
            split_index = len(current_state.full_chat_history) - 5
            to_compress = current_state.full_chat_history[:split_index]
            recent = current_state.full_chat_history[split_index:]
            new_summary = self._summarize_old_memory(to_compress)
            if current_state.long_term_memory:
                current_state.long_term_memory += f"\n[Update]: {new_summary}"
            else:
                current_state.long_term_memory = new_summary
            current_state.full_chat_history = recent
            print(f"📉 [Memory] 历史已截断。长期记忆已更新。")

        print(f"\n⚙️ [Orchestrator] 正在分析项目状态 (Supervisor Mode)...")
        
        # --- [Step 2: 构建增强型 Context] ---
        # 这里我们构造 Prompt 的文本部分
        context_str = f"Task: {current_state.user_input}\n"
        
        if current_state.long_term_memory:
            context_str += f"\n=== LONG TERM MEMORY ===\n{current_state.long_term_memory}\n========================\n"
        
        if current_state.user_feedback_queue:
            print(f"🔔 [Orchestrator] 检测到用户干预: {current_state.user_feedback_queue}")
            context_str += f"\nUSER INTERVENTION: {current_state.user_feedback_queue}\n"

        if current_state.last_error:
            context_str += f"Last Error: {current_state.last_error}\n"
            
        artifacts_str = "\nArtifacts:\n"
        if current_state.artifacts:
            for key, data in current_state.artifacts.items():
                if key == "images":
                    artifacts_str += f"- [Images]: {len(data)} image files generated by Coding Crew.\n"
                else:
                    artifacts_str += f"- [{key}]: Data available.\n"
        
        history_summary = []
        for h in current_state.full_chat_history: 
             role = h.get('role', 'unknown')
             parts = h.get('parts', [{'text': ''}])
             text = parts[0].get('text', '') if parts else ''
             history_summary.append(f"{role}: {text[:200]}...")
        history_str = "\n".join(history_summary)

        final_prompt_text = f"""
        Based on the current state, decide the next step.
        {context_str}
        {artifacts_str}
        Current Conversation:
        {history_str}
        """

        # --- [Step 3: 构造多模态 Payload] ---
        # 如果状态中有图片数据，我们需要将其加入到 parts 中
        message_parts = [{"text": final_prompt_text}]
        
        if current_state.image_data:
            print("👁️ [Orchestrator] 检测到图片输入，启用视觉分析能力...")
            message_parts.append({
                "inline_data": {
                    "mime_type": "image/jpeg", # 简单起见假设为 JPEG，实际应从文件头判断或由 input 传入
                    "data": current_state.image_data
                }
            })

        try:
            response = self.rotator.call_gemini_with_rotation(
                model_name=self.model,
                contents=[{"role": "user", "parts": message_parts}], # 这里传入包含图片的 parts
                system_instruction=self.system_instruction,
                response_schema=SupervisorDecision
            )
            
            if response:
                if isinstance(response, dict):
                    decision = SupervisorDecision.model_validate(response)
                else:
                    decision = SupervisorDecision.model_validate_json(response)
                    
                print(f"   🧠 决策: {decision.next_agent} | 原因: {decision.reasoning}")

                if decision.next_agent == "FINISH":
                    current_state.router_decision = "finish"
                    current_state.next_step = None
                    if not current_state.final_report:
                        current_state.final_report = decision.instruction
                else:
                    current_state.router_decision = "continue"
                    current_state.next_step = {
                        "agent_name": decision.next_agent, 
                        "instruction": decision.instruction
                    }
                
                current_state.user_feedback_queue = None
                current_state.last_error = None
                
            else:
                raise ValueError("Orchestrator API returned empty.")

        except Exception as e:
            print(f"❌ [Orchestrator] Planning Failed: {e}")
            current_state.last_error = str(e)
            current_state.router_decision = "human"

        return {"project_state": current_state}
