from typing import List, Optional, Dict, Any, TypedDict
from core.rotator import GeminiKeyRotator
from core.models import ProjectState, ExecutionPlan, ExecutionStep, BaseModel
from tools.memory import VectorMemoryTool
from tools.search import GoogleSearchTool

# LangGraph State 需要
class AgentGraphState(TypedDict):
    project_state: ProjectState

# ... (OrchestratorAgent, ResearcherAgent, AnalystAgent 代码保持不变) ...
# 请保留原有的其他 Agent 类

# =======================================================
# 4. CodingCrewAgent (子团队封装) - NEW!
# =======================================================

class CodingCrewAgent:
    """
    [分层架构节点]
    这是一个特殊的 Agent，它内部封装了一个 CrewAI 或 AutoGen 的子团队。
    它作为一个单一节点嵌入 LangGraph，负责处理复杂的编程、重构和审查闭环任务。
    """
    def __init__(self, rotator: GeminiKeyRotator):
        self.rotator = rotator
        # 在这里，实际项目中你可以初始化 CrewAI 的 Agents
        # from crewai import Agent, Task, Crew
        # self.coder = Agent(role='Senior Coder', goal='Write code', ...)
        # self.reviewer = Agent(role='Code Reviewer', goal='Review code', ...)

    def run(self, state: AgentGraphState) -> AgentGraphState:
        current_state = state["project_state"]
        
        if not current_state.execution_plan: return state
            
        # 获取指令，这通常是一个复杂的编程任务
        current_instruction = current_state.execution_plan[0]['instruction']
        print(f"\n🛠️ CodingCrewAgent (子团队) 启动... (任务: {current_instruction[:50]}...)")
        print("👥 正在召集内部 Crew (Coder & Reviewer)...")

        # =======================================================
        # 这里是 CrewAI / AutoGen 的内部运行逻辑 (模拟)
        # =======================================================
        # 实际代码示例:
        # task = Task(description=current_instruction, agent=self.coder)
        # crew = Crew(agents=[self.coder, self.reviewer], tasks=[task])
        # result = crew.kickoff()
        
        # 模拟 CrewAI 的输出
        simulated_code_output = f"""
# --- Generated by CrewAI Sub-team ---
# Task: {current_instruction}
# Status: Reviewed & Approved

def mission_critical_function():
    print("This code was generated by a specialized sub-team.")
    return True
"""
        
        # 将结果存入 Shared State
        current_state.code_blocks["crew_output"] = simulated_code_output
        
        # 也可以选择更新 final_report 或者追加到 chat history
        report_update = f"Coding Crew 已完成任务。生成的代码已通过内部审查。\n代码预览:\n{simulated_code_output}"
        current_state.full_chat_history.append({"role": "model", "parts": [{"text": report_update}]})
        
        print("✅ CodingCrewAgent 子团队任务完成！结果已合并。")

        # 移除已完成的计划步骤
        current_state.execution_plan.pop(0)
        return {"project_state": current_state}
