import os
import json
from tools.registry import ToolRegistry

def generate_markdown_docs(output_path: str = "agents/orchestrator/prompts/tools_instruction.md"):
    """
    根据 Registry 中的 JSON Schema 自动生成 LLM 易读的 Markdown 文档。
    """
    print(f"⚙️ Generating tool documentation from Registry...")
    
    schemas = ToolRegistry.get_all_tool_schemas()
    doc_lines = []
    
    doc_lines.append("# Available Tools Specification")
    doc_lines.append("> Auto-generated by tools/gen_docs.py. Do not edit manually.\n")
    
    for schema in schemas:
        name = schema['name']
        desc = schema['description']
        params = schema['parameters']
        
        doc_lines.append(f"## 🛠️ Tool: `{name}`")
        doc_lines.append(f"**Description**: {desc}\n")
        doc_lines.append("**Parameters**:")
        
        props = params.get('properties', {})
        required_list = params.get('required', [])
        
        if not props:
            doc_lines.append("- (No parameters required)")
        else:
            for prop_name, prop_info in props.items():
                p_type = prop_info.get('type', 'any')
                p_desc = prop_info.get('description', '')
                is_req = "**(Required)**" if prop_name in required_list else "(Optional)"
                
                # 处理 Enum
                enum_str = ""
                if 'enum' in prop_info:
                    options = ", ".join([f"'{x}'" for x in prop_info['enum']])
                    enum_str = f" [Options: {options}]"
                
                doc_lines.append(f"- `{prop_name}` ({p_type}) {is_req}: {p_desc}{enum_str}")
        
        doc_lines.append("\n---\n")
    
    # 写入文件
    # 确保目录存在
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(doc_lines))
        
    print(f"✅ Documentation generated at: {output_path}")

if __name__ == "__main__":
    generate_markdown_docs()
